### PR TITLE
Moved Asset enum out of UIImage extension

### LINKED ISSUE #112: UIImage.Asset symbol not found for Release build
I'm getting the following error when making a Release build using Xcode 7.3, Swift compiler generation setting is Fast [-O]. Is this the same issue as #57?

```
Undefined symbols for architecture x86_64:
  "type metadata for (extension in EECOffline):__ObjC.UIImage.Asset", referenced from:
      l_get_field_types_DisplayedVisit in ListVisitsModels.o
      l_get_field_types_DisplayedVisitItem in ListVisitItemsModels.o
ld: symbol(s) not found for architecture x86_64
```

### PR DESCRIPTION
**Pull request by kgrigsby59**
Fixes #112

### CODE REVIEW

**Comment by AliSoftware** [comment]
This seems great, thanks @kgrigsby59 !

Only reviewed this via the GitHub interface, will give it a go in Xcode soon but looks OK to me 👍 

Could you just add an entry in the `CHANGELOG.md` to mention the change and credit yourself? Thanks!
