### PR TITLE
Support Xcode 8 and Swift 2.3

### PR DESCRIPTION
**Pull request by ikesyo**
Supersedes #171, #176 and #178. This preserves Xcode 7.3 support.

**CocoaPods 1.1.0.rc.2 is required.**

### CODE REVIEW

**Comment by AliSoftware** [comment]
Thanks for the PR.

Don't forget to add s CHANGELOG entry; it would be nice to mention the original author of the related PR that made the effort on the 2.3 port as well in that entry

**Comment by ikesyo** [comment]
Updated!

**Comment by AndrewSB** [comment]
hey @ikesyo, I tried to compile this on Xcode 8, I saw some issues with dependencies - is this PR supposed to get swiftgen all the way up to Xcode 8 support, or should updating the dependencies be another pull request?

**Comment by ikesyo** [comment]
@AndrewSB This should be fine on Xcode 8: https://travis-ci.org/AliSoftware/SwiftGen/jobs/163091175. I'm not sure what the issues are you are facing.

**Comment by AndrewSB** [comment]
@dzenbot I do see that popup, but I'm having errors past that. Something related to `if let` syntax in `GenumKit`, and missing `SWIFT_VERSION` flags in the cocoapods frameworks:

screen shot 2016-10-03 at 8 11 38 pm

**Comment by AndrewSB** [comment]
Let me submit a PR with the changes that I needed to get swiftgen to build, so we can talk about if they're needed or not 👍

**Comment by AndrewSB** [comment]
(submitted #179)

yeah! It is super weird. Strange that someone hasn't contributed that change to Cocoapods 🤔

**Comment by AndrewSB** [comment]
I do, thanks @dzenbot

**Comment by ikesyo** [comment]
@AndrewSB You need CocoaPods 1.1.0.rc.2 to use Xcode 8.

**Comment by ikesyo** [comment]
> Interesting. For the frameworks needing the SWIFT_VERSION flag, I realized that Cocoapods isn't helping with that sometimes, so I fixed it this way on my project

@dzenbot CocoaPods 1.1.0 (currently rc.2) now handles the setting correctly.

**Comment by AndrewSB** [comment]
ahh, I see! I'll update to their release candidate then. Thank you for your work @ikesyo 😃

**Comment by AndrewSB** [comment]
Apologies on dragging this out, but I'm still having issues building this branch:

```
== Building Binary ==

set -o pipefail && xcrun -sdk macosx swiftc -O -o build/Release/swiftgen -F build/Release/PathKit -F build/Release/Stencil -F build/Release/Commander -F build/Release/GenumKit/ -framework PathKit -framework Stencil -framework Commander -framework GenumKit swiftgen-cli/*.swift | xcpretty -c
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected ':' following argumant label and parameter name
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected type
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected ',' separator
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
                                                                     ,
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected type
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected ',' separator
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
                                                                     ,
swiftgen-cli/ArgumentsUtils.swift:7:8: error: module compiled with Swift 2.3 cannot be imported in Swift 3.0: /Users/asb/Developer/SwiftGen/build/Release/Commander/Commander.framework/Modules/Commander.swiftmodule/x86_64.swiftmodule
import Commander
       ^
rake aborted!
Command failed with status (1): [set -o pipefail && xcrun -sdk macosx swift...]
/Users/asb/Developer/SwiftGen/Rakefile:24:in `xcpretty'
/Users/asb/Developer/SwiftGen/Rakefile:64:in `block in <top (required)>'
Tasks: TOP => install => install:light => build
(See full trace by running task with --trace)
```

Everything compiles, but the Rakefile fails after that, whilst building the swiftgen binary. Any idea what that could be?

**Comment by kgrigsby59** [comment]
@AndrewSB You could run it as ```TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 rake install``` but a better solution would be to specify a toolchain in the xcrun command in the rakefile.

**Comment by AndrewSB** [comment]
that was perfect, thanks @kgrigsby59

**Comment by AndrewSB** [comment]
@AliSoftware this looks good to go, can it be merged in?

**Comment by AliSoftware** [comment]
👍

**Comment by AliSoftware** [comment]
The only thing that prevents me to merge that is having some time to do an official release (I keep this PR open to remind me of doing a homebrew release once I've got enough time). That shouldn't take that long but I've been traveling lately and didn't use my Mac much so will need some time off to catch up on all those pending PRs on my various OSS work soon, sorry for the delay!

**Comment by plivesey** [comment]
@ikesyo I'm not sure if it's something to do with my personal machine, but `rake install` doesn't seem to work for me on this branch:

```
== Building Binary ==

xcrun -sdk macosx swiftc -O -o build/Release/swiftgen -F build/Release/PathKit -F build/Release/Stencil -F build/Release/Commander -F build/Release/GenumKit/ -framework PathKit -framework Stencil -framework Commander -framework GenumKit swiftgen-cli/*.swift
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected ':' following argumant label and parameter name
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected type
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected ',' separator
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
                                                                     ,
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected type
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
swiftgen-cli/ArgumentsUtils.swift:12:71: error: expected ',' separator
func checkPath(type: String, assertion: Path -> Bool) -> (Path throws -> Path) {
                                                                      ^
                                                                     ,
swiftgen-cli/ArgumentsUtils.swift:7:8: error: module compiled with Swift 2.3 cannot be imported in Swift 3.0.1: /Users/plivesey/Repo/temp/SwiftGen/build/Release/Commander/Commander.framework/Modules/Commander.swiftmodule/x86_64.swiftmodule
import Commander
       ^
rake aborted!
Command failed with status (1): [xcrun -sdk macosx swiftc -O -o build/Relea...]
/Users/plivesey/Repo/temp/SwiftGen/Rakefile:26:in `xcpretty'
/Users/plivesey/Repo/temp/SwiftGen/Rakefile:64:in `block in <top (required)>'
Tasks: TOP => install => install:light => build
(See full trace by running task with --trace)
```

It seems like `swiftc` is running with Swift 3, but everything is compile with Swift 2.3. My guess is we need to add a flag to:

`  xcpretty %Q(xcrun -sdk macosx swiftc -O -o #{BUILD_DIR}/#{BIN_NAME} #{search_paths}/ #{frameworks} swiftgen-cli/*.swift)`

which includes the swift version. I can't work out how to do this though...

Thoughts? Or is this working for you?

**Comment by plivesey** [comment]
Looks like it gets further here if you change to:

`xcpretty %Q(TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 xcrun -sdk macosx swiftc -O -o #{BUILD_DIR}/#{BIN_NAME} #{search_paths}/ #{frameworks} swiftgen-cli/*.swift)`

But then fails later when it does other toolchain stuff...which I don't understand :/

**Comment by ikesyo** [comment]
@plivesey Did you see https://github.com/AliSoftware/SwiftGen/pull/179#issuecomment-251478255? Specifying a toolchain explicitly in Rakefile makes it difficult to support both Xcode 7.3 and Xcode 8.

**Comment by AliSoftware** [comment]
Finally, I've found some time to merge this!

@plivesey @ikesyo @AndrewSB I've fixed the Rakefile in aa6ed1d595351e9ec1896dbf998069ad710e95da so that now it:

* auto-selects the latest Xcode 8 found in your machine… even if it's not your default Xcode (using `DEVELOPER_DIR=…` instead of forcing you to `xcode-select -s`)
* raises if no Xcode 8 is found on your machine at all
* forces `TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3` too

So now SwiftGen is officially Swift 2.3 (and thus only supporting Xcode 8)! 🎉 

_Next step: Swift 3.0 conversion… but that's for another day!_

**Comment by zmwangx** [comment]
@AliSoftware Would you consider putting out a patch release for Homebrew? Thanks.

**Comment by AliSoftware** [comment]
@zmwangx That's the plan 👍

**Comment by zmwangx** [comment]
Cool, thanks.

**Comment by AndrewSB** [comment]
🎉🎉🎉 thanks @AliSoftware!

**Comment by AliSoftware** [comment]
3.0.1 should already be available thru CocoaPods.
[Pull Request for the Homebrew release has been open](https://github.com/Homebrew/homebrew-core/pull/6663), waiting for the Homebrew crew to merge.

**Comment by plivesey** [comment]
Thanks @AliSoftware and @ikesyo :). I couldn't work this all out on my own, but working after rebasing. 🎉
