### ISSUE TITLE
UIImage.Asset symbol not found for Release build

### ISSUE THREAD

**Issue by kgrigsby59** [AliSoftware/SwiftGen#112]
I'm getting the following error when making a Release build using Xcode 7.3, Swift compiler generation setting is Fast [-O]. Is this the same issue as #57?

```
Undefined symbols for architecture x86_64:
  "type metadata for (extension in EECOffline):__ObjC.UIImage.Asset", referenced from:
      l_get_field_types_DisplayedVisit in ListVisitsModels.o
      l_get_field_types_DisplayedVisitItem in ListVisitItemsModels.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by larryonoff** [comment]
It's probably the issue from Xcode 7.3 that appears when you have internal structs / enums in ObjC classes.

I had to move internal structs / enums out of ObjC classes.

**Comment by AliSoftware** [comment]
Yes, that's related to the same Swift bug we talk about in #56 and #57 and that has been [confirmed by an engineer of the Swift compiler team on Twitter](https://twitter.com/aligatr/status/669970159529025536).

Only workaround until the Swift compiler is fixed is indeed to extract the internal structs or enums out of the ObjC class, like I had to do for the Storyboard (we had an internal `UIStoryboard.Scene` type that is now an external `StoryboardScene` in the current templates to work around this).

I should update all the templates to be sure to avoid this bug not only in UIStoryboards like I did, but also in `UIColor` and `UIImage` too as it seem to affect every template.

_Note: I'm quite busy with many other projects right now so sorry for not having replied earlier. A Pull Request modifying the templates to extract the inner types as top-level types would be welcome (and should be quite easy) if you want this to be resolved quickly, as I'm afraid I still won't have much time to do it myself until a week or two._

**Comment by kgrigsby59** [comment]
@AliSoftware Would you like something like the following?

```
enum Asset: String {
    case GreenApple = "Green-Apple"
    case RedApple = "Red-Apple"
    
    var image: UIImage {
        return UIImage(named: self.rawValue)!
    }
}

let greenAppleAsset = Asset.GreenApple
let greenAppleAssetImage = Asset.GreenApple.image
```

**Comment by AliSoftware** [comment]
@kgrigsby59 seems about right. Just extracting the `Asset` to be at top level like you did should be enough indeed.

Just to be clear: I'd still keep the `init(asset: Asset)` constructor in `extension UIImage`; just the enum needs to be moved out I think.

**Comment by AbsolutRenal** [comment]
Hi,
We got the same issue last week. Moving enum out from the class did resolve the issue. But we finally solved the issue by setting `Optimization level` (for Swift Compiler) to `None [-Onone]` as each time we used swiftgen, the enum was generated inside class

**Comment by kgrigsby59** [comment]
@AbsolutRenal As a workaround I'm currently using the new stencil from my pull request and referencing it with the --templatePath option of swiftgen.

**Comment by AndrewSB** [comment]
@AbsolutRenal I don't have an optimization level `None [-Onone]`, my none is shown as `None [-O0]`, and it doesn't resolve the error. Any suggestions on fixing this?
